# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='Anonymous', max_length=32)),
                ('media_url', models.URLField()),
                ('comment', models.CharField(max_length=400)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-datetime',),
            },
        ),
    ]
