# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 00:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favit', '0002_auto_20160526_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fav',
            old_name='user_name',
            new_name='user',
        ),
    ]
