# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('favit', '0003_auto_20160526_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='fav',
            name='unique_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='fav',
            name='media_url',
            field=models.URLField(max_length=400),
        ),
    ]
